SELECT tbl_VendasDetKitProd_NRSerie.CodVendasDETKitProd_CVDKit AS CodOperacao, tbl_VendasDetKitProd_NRSerie.Cod_NrSerie_CVDKit AS CodCR, tbl_VendasDetKitProd_NRSerie.Observacao_CVDKit AS Usuario
FROM tbl_VendasDetKitProd_NRSerie
WHERE (((tbl_VendasDetKitProd_NRSerie.CodVendasDETKitProd_CVDKit)=2));
