SELECT tbl_rot_vendasDetalhadas.Cod_venda, tbl_rot_vendas.Dt_Hr_venda, tbl_cad_clientes.NomeRazaoSocial_Cliente AS Cliente, tbl_cad_forma_retiradaEstoque.forma_retiradaEstoque
FROM (((((tbl_rot_vendasDetalhadas LEFT JOIN tbl_cad_prodserv ON tbl_rot_vendasDetalhadas.Cod_produto = tbl_cad_prodserv.Cod_ProdServ) LEFT JOIN tbl_VendasDET_NRSerie ON tbl_rot_vendasDetalhadas.Cod_VendasDet = tbl_VendasDET_NRSerie.CodVendasDET_CVNS) LEFT JOIN tbl_NrSerie_Prod ON tbl_VendasDET_NRSerie.Cod_NrSerie_CVNS = tbl_NrSerie_Prod.cod_NrSerie) LEFT JOIN tbl_rot_vendas ON tbl_rot_vendasDetalhadas.Cod_venda = tbl_rot_vendas.Cod_venda) LEFT JOIN tbl_cad_forma_retiradaEstoque ON tbl_rot_vendas.Cod_formaRetiradaEstoque = tbl_cad_forma_retiradaEstoque.cod_retiradaEstoque) LEFT JOIN tbl_cad_clientes ON tbl_rot_vendas.Cod_cliente = tbl_cad_clientes.Cod_cliente
WHERE (((tbl_rot_vendas.Grupo_vendas)=12) AND ((tbl_cad_prodserv.Grupo_prodServ)="produto"))
GROUP BY tbl_rot_vendasDetalhadas.Cod_venda, tbl_rot_vendas.Dt_Hr_venda, tbl_cad_clientes.NomeRazaoSocial_Cliente, tbl_cad_forma_retiradaEstoque.forma_retiradaEstoque
HAVING (((Sum(tbl_rot_vendasDetalhadas.QutLiberada_Estoque))>0));

UNION ALL SELECT tbl_rot_MovEstoque.CodVenda_RetiradaEst AS CodVenda, tbl_rot_MovEstoque.dtHrRetiradaEst, tbl_cad_clientes.NomeRazaoSocial_Cliente AS Cliente, tbl_cad_forma_retiradaEstoque.forma_retiradaEstoque AS Tipo
FROM ((tbl_rot_MovEstoque LEFT JOIN ((tbl_rot_MovEstoque_Prod LEFT JOIN tbl_NrSerie_Prod ON tbl_rot_MovEstoque_Prod.CodProd_PME_ENTRADA = tbl_NrSerie_Prod.CodProdServ_Nrserie) LEFT JOIN tbl_NrSerie_Prod AS tbl_NrSerie_Prod_1 ON tbl_rot_MovEstoque_Prod.CodProd_PME_SAIDA = tbl_NrSerie_Prod_1.CodProdServ_Nrserie) ON tbl_rot_MovEstoque.CodRetiradaEst = tbl_rot_MovEstoque_Prod.CodMovEstoque) LEFT JOIN tbl_cad_forma_retiradaEstoque ON tbl_rot_MovEstoque.FormaRetiradaEst = tbl_cad_forma_retiradaEstoque.cod_retiradaEstoque) LEFT JOIN (tbl_cad_clientes RIGHT JOIN tbl_rot_vendas ON tbl_cad_clientes.Cod_cliente = tbl_rot_vendas.Cod_cliente) ON tbl_rot_MovEstoque.CodVenda_RetiradaEst = tbl_rot_vendas.Cod_venda
GROUP BY tbl_rot_MovEstoque.CodVenda_RetiradaEst, tbl_rot_MovEstoque.dtHrRetiradaEst, tbl_cad_clientes.NomeRazaoSocial_Cliente, tbl_cad_forma_retiradaEstoque.forma_retiradaEstoque, tbl_rot_MovEstoque_Prod.liberado_estoque
HAVING (((tbl_rot_MovEstoque_Prod.liberado_estoque)=Yes));
