SELECT tbl_cad_grupo_comissionista.Cod_Grupo_comissionista, tbl_cad_grupo_comissionista.Grupo_comissionista, tbl_cad_grupo_comissionista.Descricao_grupo_comissionista, tbl_cad_grupo_comissionista.ComissaoFixa_procent_grupoComissionista, tbl_cad_grupo_comissionista.ComissaoFixa_Valor_grupoComissionista
FROM tbl_cad_grupo_comissionista;
