SELECT DateSerial(Year([Dt_Hr_venda]),Month([Dt_Hr_venda]),Day([Dt_Hr_venda])) AS Dt_Hr_vend, Sum(tbl_cad_formasPagamentoVENDASDET.Valor_FormaPagVendasDet) AS [Valor Entrada], Sum(0) AS [Valor Saída], tbl_cad_formasPagamento.Nome_FormaPagamento AS [Forma de Pagamento], "Venda" AS Origem, "Receita" AS Tipo
FROM TMP_formasPagamento LEFT JOIN ((tbl_rot_vendas RIGHT JOIN tbl_cad_formasPagamentoVENDASDET ON tbl_rot_vendas.Cod_venda = tbl_cad_formasPagamentoVENDASDET.Cod_Venda) RIGHT JOIN tbl_cad_formasPagamento ON tbl_cad_formasPagamentoVENDASDET.Cod_formasPagamento = tbl_cad_formasPagamento.Cod_formasPagamento) ON TMP_formasPagamento.Cod_formasPagamento = tbl_cad_formasPagamento.Cod_formasPagamento
GROUP BY DateSerial(Year([Dt_Hr_venda]),Month([Dt_Hr_venda]),Day([Dt_Hr_venda])), tbl_cad_formasPagamento.Nome_FormaPagamento, "Venda", "Receita", TMP_formasPagamento.Permitido_FormaPagamento, tbl_rot_vendas.Cod_formaRetiradaEstoque, tbl_rot_vendas.VendaFinalizada_vendas
HAVING (((DateSerial(Year([Dt_Hr_venda]),Month([Dt_Hr_venda]),Day([Dt_Hr_venda]))) Between [Formulários]![Frm_totalporvendaporperiodo]![TxtDtInicial] And [Formulários]![Frm_totalporvendaporperiodo]![TxtDtFinal]+1) AND ((TMP_formasPagamento.Permitido_FormaPagamento)=Yes) AND ((tbl_rot_vendas.Cod_formaRetiradaEstoque)=1) AND ((tbl_rot_vendas.VendaFinalizada_vendas)=Yes));

union all

SELECT tbl_rot_PagCli_contasReceber.[datapag_contasreceberdet] AS Dt_Hr_vend, Sum(tbl_rot_PagCli_contasReceber.[valorpagopagcli_CR]) AS [Valor Entrada], Sum(0) AS [Valor Saída], tbl_cad_formasPagamento.Nome_FormaPagamento AS [Forma de Pagamento], "Contas a Receber" AS Origem, "Receita" AS Tipo
FROM (TMP_formasPagamento LEFT JOIN tbl_cad_formasPagamento ON TMP_formasPagamento.Cod_formasPagamento = tbl_cad_formasPagamento.Cod_formasPagamento) LEFT JOIN tbl_rot_PagCli_contasReceber ON tbl_cad_formasPagamento.Cod_formasPagamento = tbl_rot_PagCli_contasReceber.FormaPagPagCli_CR
GROUP BY tbl_rot_PagCli_contasReceber.[datapag_contasreceberdet], tbl_cad_formasPagamento.Nome_FormaPagamento, "Contas a Receber", "Receita", TMP_formasPagamento.Permitido_FormaPagamento
HAVING (((tbl_rot_PagCli_contasReceber.[datapag_contasreceberdet]) Between [Formulários]![Frm_totalporvendaporperiodo]![TxtDtInicial] And [Formulários]![Frm_totalporvendaporperiodo]![TxtDtFinal]+1) AND ((TMP_formasPagamento.Permitido_FormaPagamento)=Yes));


UNION ALL SELECT DateSerial(Year([dtmovimento_lanccaixa]),Month([dtmovimento_lanccaixa]),Day([dtmovimento_lanccaixa])) AS Dt_Hr_vend, Sum(tbl_rot_LancCaixa.Valor_LancCaixa) AS [Valor Entrada], Sum(0) AS [Valor Saída], tbl_cad_formasPagamento.Nome_FormaPagamento AS [Forma de Pagamento], "Caixa" AS Origem, "Receita" AS Tipo FROM TMP_formasPagamento LEFT JOIN (tbl_rot_LancCaixa RIGHT JOIN tbl_cad_formasPagamento ON tbl_rot_LancCaixa.CodFormaPag_LancCaixa = tbl_cad_formasPagamento.Cod_formasPagamento) ON TMP_formasPagamento.Cod_formasPagamento = tbl_cad_formasPagamento.Cod_formasPagamento GROUP BY DateSerial(Year([dtmovimento_lanccaixa]),Month([dtmovimento_lanccaixa]),Day([dtmovimento_lanccaixa])), tbl_cad_formasPagamento.Nome_FormaPagamento, "Caixa", "Receita", tbl_rot_LancCaixa.Tipo_LancCaixa, TMP_formasPagamento.Permitido_FormaPagamento HAVING (((DateSerial(Year([dtmovimento_lanccaixa]),Month([dtmovimento_lanccaixa]),Day([dtmovimento_lanccaixa]))) Between [Formulários]![Frm_totalporvendaporperiodo]![TxtDtInicial] And [Formulários]![Frm_totalporvendaporperiodo]![TxtDtFinal]+1) AND ((tbl_rot_LancCaixa.Tipo_LancCaixa)="crédito") AND ((TMP_formasPagamento.Permitido_FormaPagamento)=Yes));
